### ISSUE TITLE
Unable to handle 0 FPS in renditions

### ISSUE THREAD

**Issue by yondonfu** [livepeer/verification-classifier#119]
## Background

go-livepeer currently supports passthrough FPS transcoding (i.e. set the FPS of a transcoded rendition to the source FPS) by setting the rendition FPS to 0. This results in a division by 0 error in the verifier because the `frame_rate` field of a rendition in the API request is set to 0:

```
[2020-07-15 14:58:13,431] ERROR in app: Exception on /verify [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/verifier/api/api.py", line 182, in post_route
    predictions = verifier.verify(verification['source'], data['renditions'])
  File "/verifier/verifier/verifier.py", line 137, in verify
    pre_verification = self.pre_verify(source, rendition)
  File "/verifier/verifier/verifier.py", line 94, in pre_verify
    rendition['frame_rate'] = 0.99 <= fps / float(rendition['frame_rate']) <= 1.01
ZeroDivisionError: float division by zero
```

## Desired Solution

Get the source FPS and if the expected rendition FPS is 0 compare the the actual rendition FPS with the source FPS (instead of with the expected rendition FPS).

## Alternatives

go-livepeer could populate the `frame_rate` field of a rendition in the API request with the source FPS if the rendition FPS is set to 0. But, go-livepeer doesn't have easy access to the source FPS right now so it might be easier to just add this logic to the verifier which would be able to get the source FPS via `rendition_capture.get(cv2.CAP_PROP_FPS)`.

**Comment by yondonfu** [comment]
Closed by #121
