### ISSUE TITLE
KeyError: 'temporal_gaussian_difference' when using the API

### ISSUE THREAD

**Issue by yondonfu** [livepeer/verification-classifier#43]
After launching the API, I tried submitting the following curl request (taken from the API README):

```
curl localhost:5000/verify -d '{"source": "https://storage.googleapis.com/livepeer-verifier-originals/-3MYFnEaYu4.mp4", "renditions": ["https://storage.googleapis.com/livepeer-verifier-renditions/1080p_black_and_white/-3MYFnEaYu4.mp4", "https://storage.googleapis.com/livepeer-verifier-renditions/720p_watermark/-3MYFnEaYu4.mp4"], "model": "https://storage.googleapis.com/verification-models/verification.tar.gz"}'  -H 'Content-Type: application/json'
```

and I encountered the following error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/scripts/api.py", line 31, in post_route
    predictions = verify(source_file, renditions, do_profiling, max_samples, model_file, model_name)
  File "/scripts/verifier.py", line 47, in verify
    asset_processor = video_asset_processor(original_asset, renditions_list, metrics_list, seconds, max_samples, do_profiling)
  File "/scripts/video_asset_processor.py", line 62, in __init__
    self.metrics[self.original_path] = self.compute(self.original, self.original_path, self.dimensions)
  File "/scripts/video_asset_processor.py", line 169, in compute
    print(frame_pos, rendition_metrics[frame_pos]['temporal_gaussian_difference'])
KeyError: 'temporal_gaussian_difference'
```

EDIT: I also run into the same error when using local assets with the following request:

```
curl localhost:5000/verify -d '{"source": "stream/sources/-q5KjVtc55s.mp4", "renditions": ["stream/1080p_watermark/-q5KjVtc55s.mp4", "stream/720p_watermark/-q5KjVtc55s.mp4"], "model": "https://storage.googleapis.com/verification-models/verification.tar.gz"}'  -H 'Content-Type: application/json'
```

**Comment by ndujar** [comment]
Fixed in 0a2dce937d9adf71b85d98367b0dd6d81ae27472
