### ISSUE TITLE
Audio comparison failing

### ISSUE THREAD

**Issue by j0sh** [livepeer/verification-classifier#78]
Getting this error on master (along with https://github.com/livepeer/verification-classifier/pull/77 applied)

```
Audio file /tmp/eeac641d-e5a8-4ba7-a771-0a9f623c8887_audio.wav available in file system
[2019-11-26 23:45:33,027] ERROR in app: Exception on /verify [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "scripts/api.py", line 131, in post_route
    model_name)
  File "/scripts/verifier.py", line 102, in verify
    pre_verification = pre_verify(source, rendition)
  File "/scripts/verifier.py", line 44, in pre_verify
    rendition['audio_dist'] = np.linalg.norm(source_file_series-rendition_file_series)
ValueError: operands could not be broadcast together with shapes (96256,6) (89088,2)
```

**Comment by ndujar** [comment]
Fixed in 759ee6f64823e75b70ce5356202527c346006ad8

**Comment by j0sh** [comment]
Still getting the same error on master

```
Audio file /tmp/7ee813fb-959a-4872-8b14-65ff6fcc5b2d_audio.wav available in file system
[2019-11-27 16:05:55,428] ERROR in app: Exception on /verify [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "scripts/api.py", line 131, in post_route
    model_name)
  File "/scripts/verifier.py", line 102, in verify
    pre_verification = pre_verify(source, rendition)
  File "/scripts/verifier.py", line 44, in pre_verify
    rendition['audio_dist'] = np.linalg.norm(source_file_series-rendition_file_series)
ValueError: operands could not be broadcast together with shapes (96256,6) (89088,2)
```

**Comment by j0sh** [comment]
Fixed by https://github.com/livepeer/verification-classifier/commit/80bd78e1745e6044c88413fc03ecafd4e3fdc81d
